'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iPlayer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _24_cinzento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("24_cinzento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _400_F_6127188_8GYwCRwxwgtTNQv9gtODx7l4BdshkHSj_transparente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("400_F_6127188_8GYwCRwxwgtTNQv9gtODx7l4BdshkHSj_transparente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _410() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("410", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _411() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("411", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _500_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("500_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property acerca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acerca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property audioandradio_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audioandradio_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlueDisc11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueDisc11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cdrwblank_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cdrwblank-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Doc_MusicPlaylist_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doc-MusicPlaylist_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Doc_MusicPlaylist_32d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doc-MusicPlaylist_32d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundoP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundoP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gh1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gh1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Glass_Music_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Glass-Music_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_List_Add_32_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-List-Add-32_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_Media_Playlist_Repeat_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-Media-Playlist-Repeat-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_Media_Playlist_Repeat_32_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-Media-Playlist-Repeat-32_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_Media_Playlist_Repeat_one() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-Media-Playlist-Repeat_one", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_Media_Playlist_Shuffle_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-Media-Playlist-Shuffle-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gnome_Media_Playlist_Shuffle_32_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gnome-Media-Playlist-Shuffle-32_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iPod___Black_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iPod_-_Black_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iPod___Black_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iPod_-_Black_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iTunes_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTunes-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iTunes_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iTunes-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property juj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("juj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property m1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_find_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_find-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MultiSelec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MultiSelec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Music() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Music", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Music_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Music_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property music_file_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("music-file-24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mute_off1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mute_off1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mute_on1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mute_on1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nada_Em_Reprod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nada_Em_Reprod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nada_seleccionado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nada_seleccionado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nopCapa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nopCapa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NopCapaCD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NopCapaCD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property op() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("op", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property op_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("op copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pendrive_128x128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pendrive_128x128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pendrive_64x64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pendrive_64x64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_fwd_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_fwd-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_fwd_32_enabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_fwd-32_enabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_fwd_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_fwd_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_pause_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_pause_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_rew_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_rew-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_rew_32_enabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_rew-32_enabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_rew_enabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_rew_enabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_rew_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_rew_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_stop_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_stop-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_stop_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_stop_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playerpp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerpp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playerpp_enabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerpp_enabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playerpp_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerpp_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search-16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sem_capa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sem_capa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property semc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("semc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property StepForwardNormalBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StepForwardNormalBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
